# Generated by Django 3.0.12 on 2021-07-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larder', '0001_initial'),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='larder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='user',
            name='larder_id',
        ),
        migrations.AlterField(
            model_name='shoppingauditentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larder.Item'),
        ),
        migrations.AlterField(
            model_name='shoppingauditentry',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larder.User'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Larder',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
