# Generated by Django 3.0.12 on 2021-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_shelf_life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_purchased_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_used_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
