# Generated by Django 3.0.12 on 2021-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larder', '0002_auto_20210708_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Larder',
        ),
    ]
